### PR TITLE
Refactor Schema::make() to dynamically create class name from type.

### PR DESCRIPTION
**Pull request by coderabbi**
re: #7  

Once I had it written in the comment, simple enough to put it in the code... I'm not in love with it, but as an intermediate step? 🤷‍♂️

### CODE REVIEW

**Comment by coderabbi** [comment]
Okay, not sure how you feel about it, but Scrutinizer is happy with `Schema.php` now.

**Comment by shadowhand** [comment]
Looks good! Can you squash to 1 commit, please?

**Comment by coderabbi** [comment]
:dash:

**Review by shadowhand — APPROVED** [review]

**Comment by shadowhand** [comment]
Thanks!

**Comment by shadowhand** [comment]
Released in 0.5.0.

**Pull request merged**
